# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a2e4739ca54a4851af4d09281e833e414526e6e2fa5edb5d819523600c59875726ae9749909a3a745ffc056b060ab9f0866d718c9925b173f852ae9f0f902f3

test:
  secret_key_base: 591e07eb5a6192af8b86985542bb96e870c805dfb193042c0f62fb58cb653a8137160200f6b91bc5b3223b77b0d353fdad15fd3c6fa44aee699d886e46d55b26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
